# NumPy Array Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

## <span style="color:blue"> 1. Import `Numpy` with the `alias` `np`</span>

In [2]:
import numpy as np

<hr>
<br>
<br>

## <span style="color:blue"> 2. Create a numpy array out of a python list </span>

### A. Numpy Arrays: `int` datatype

In [4]:
py_list = [1, 2, 3, 4, 5]

#### Convert `py_list` into `numpy` array and store in `np_arr`

In [5]:
np_arr = np.array(py_list)

#### Grab the `type` of `np_arr` and `print` to screen. 

In [11]:
print(np_arr.dtype)

int32


#### Print `np_arr` to screen... Take note of the `int` values.

In [8]:
print(np_arr)

[1 2 3 4 5]


#### Print `shape` of `np_arr` to screen. 

In [9]:
print(np_arr.shape)

(5,)


<br>

### B. Numpy Arrays: `int` and `str` mixed datatype

#### Change `py_list` to include a `string`

In [12]:
py_list = [1, 2, 3, 4, 5, "six"]

#### Convert `py_list`, into `numpy` array and store in `np_arr`

In [17]:
np_arr = np.array(py_list)

#### Grab the `type` of `np_arr` and `print` to screen. 

In [18]:
print(type(np_arr))
print(np_arr.dtype)


<class 'numpy.ndarray'>
<U11


#### Print `np_arr` to screen... notice something different about the `int` values?

In [19]:
print(np_arr)

['1' '2' '3' '4' '5' 'six']


#### Print `shape` of `np_arr` to screen. Notice the change?

In [20]:
print(np_arr.shape)

(6,)


<hr>
<br>
<br>

## <span style="color:blue"> 3. Create an array of 10 zeros, store in variable `zero10`. </span>

```python
[0 0 0 0 0 0 0 0 0 0]
```

In [23]:
zero10 = np.zeros(10)
zero10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Grab the `shape` of `zero10` and store it in `zero10shp` 

In [35]:
zero10shp = zero10.shape
zero10shp

(10,)

#### Test Yourself:

**Remember:** If the cells below run without an **AssertionError**, this means that you've completed the task correctly —**otherwise**, you have made a mistake and must alter your code above, then try to run Assert cells once again.

In [26]:
np.testing.assert_array_equal(zero10, np.array([0,0,0,0,0,0,0,0,0,0]))

In [27]:
assert zero10shp == (10,)

<hr>
<br>
<br>

## <span style="color:blue"> 4. Create an array of 10 ones, store in variable `one10` </span>
```python
[1 1 1 1 1 1 1 1 1 1]
```

In [32]:
one10 = np.ones(10)
one10

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Grab the `shape` of `one10` and store it in `one10shp` 

In [38]:
one10sph = one10.shape
one10shp

(10,)

#### Test Yourself:

**Remember:** If the cells below run without an **AssertionError**, this means that you've completed the task correctly —**otherwise**, you have made a mistake and must alter your code above, then try to run Assert cells once again.

In [39]:
np.testing.assert_array_equal(one10, np.array([1,1,1,1,1,1,1,1,1,1]))

In [40]:
assert one10shp == (10,)

<hr>
<br>
<br>

## <span style="color:blue"> 5. Create an array of 10 fives, store it in variable `five10` </span>

```python
[5 5 5 5 5 5 5 5 5 5]
```

In [42]:
five10 = np.zeros(10) + 5
five10

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Test Yourself:

**Remember:** If the cells below run without an **AssertionError**, this means that you've completed the task correctly —**otherwise**, you have made a mistake and must alter your code above, then try to run Assert cells once again.

In [43]:
np.testing.assert_array_equal(five10, np.array([5,5,5,5,5,5,5,5,5,5]))

<hr>
<br>
<br>

## <span style="color:blue"> 6. Create an array of the integers from 10 to 50, store in variable `ints1050` </span>

```python
[10 11 12 13 ... 48 49 50]
```

In [52]:
ints1050 = np.arange(10,51)
ints1050

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Test Yourself:

**Remember:** If the cells below run without an **AssertionError**, this means that you've completed the task correctly —**otherwise**, you have made a mistake and must alter your code above, then try to run Assert cells once again.

In [53]:
np.testing.assert_array_equal(ints1050, np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50]))

<hr>
<br>
<br>

## <span style="color:blue"> 7. Create an array of all the *even* integers from 10 to 50, store in variable `even_ints1050` </span>

```python
[10 12 ... 48 50]
```

In [60]:
even_ints1050 = np.arange(10,51,2)
even_ints1050

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Test Yourself:

**Remember:** If the cells below run without an **AssertionError**, this means that you've completed the task correctly —**otherwise**, you have made a mistake and must alter your code above, then try to run Assert cells once again.

In [61]:
np.testing.assert_array_equal(even_ints1050, np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50]))

<hr>
<br>
<br>

## <span style="color:blue"> 8. Generate an array of 20 *linearly spaced points* between 0 and 1, output array must include both 0 and 1 —store it in `lin20` </span>

```python
[0 ... 1]
```

In [64]:
lin20 = np.linspace(0,1, 20)
lin20

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### Test Yourself:

**Remember:** If the cells below run without an **AssertionError**, this means that you've completed the task correctly —**otherwise**, you have made a mistake and must alter your code above, then try to run Assert cells once again.

In [ ]:
np.testing.assert_array_equal(lin20, np.array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]))

<hr>
<br>
<br>

## <span style="color:blue"> 9. Use NumPy's Random Module to generate a random number between 0 and 1 </span>

Some ex results: `[0.55288314]`, `[0.20471546]`, etc

In [66]:
np.random.rand(1)

array([0.6245132])

**No Assertion Test** for this one, as **your answer will be randomly generated!**

<hr>
<br>
<br>

## <span style="color:blue"> 10. Use NumPy's Random Module to generate an array of 25 random numbers sampled from the *Standard Normal Distribution*, store it in variable `ran_arr`. </span>

The Standard Normal Distribution is a distribution of numbers between `-1` and `1` where the `mean` is `0`.  

In [68]:
ran_arr = np.random.randn(25)
ran_arr

array([-0.28868258,  0.32885488, -1.95032955, -0.01087695,  0.11162547,
       -0.63068557, -0.61593496, -1.07279002,  1.17679803, -0.25145112,
       -0.25323604,  0.87540739, -0.53772784,  0.2184282 , -0.30186367,
        0.70967794,  0.27583198,  0.8649772 , -1.16783431,  0.64083438,
       -1.13655643, -0.25649469,  0.31923228,  1.73361127, -0.40472203])

#### Caluculate the `max()` and `argmax()`, store in variables `mx` and `argmx`. `print` your results, do they make sense?

In [71]:
print(ran_arr.max())
print(ran_arr.argmax())

1.7336112711211036
23


#### Calculate the `min()` and `argmin()`, store in variables `mn` and `argmn`. `print` your results, do they make sense?

In [75]:
mn = ran_arr.min()
argmn = ran_arr.argmin()
print(mn, argmn)

-1.9503295546967083 2


**No Assertion Test** for this one, as **your answer will be randomly generated!**