# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python, is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

<hr>
<br>
<br>

## Using NumPy

The anaconda distribution of python comes with the NumPy library pre-installed, so all we have to do is import it!
You can import any pre-installed library, as such:

#### Import Format: 
```python
import library_name as alias
```

<br>

#### 1. Import `numpy`

```python
import numpy as np
```

In [2]:
import numpy as np


<br>

#### 2. install `pyreadline` library to activate the `.` + `tab` complete

```python 
import sys
!{sys.executable} -m pip install pyreadline
```

In [4]:
import sys
!{sys.executable} -m pip install pyreadline

<br>

#### 3. You may need to upgrade the pip package manager

```python
!{sys.executable} -m pip install --upgrade pip
```

In [5]:
!{sys.executable} -m pip install --upgrade pip


  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3


<br>

#### 4. import `pyreadline` to gain its functionality 

```python
import pyreadline
```

In [6]:
import pyreadline

<br>

#### 5. `.` + `tab` to explore library

```python
np.<tab>
```

In [ ]:
np.

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: arrays, and number generation. Let's start by discussing arrays.

<hr>
<br>
<br>

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional arrays and matrices are 2-dimensional. We will be focusing our efforts on 1-D Arrays!

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List
We can create an array by directly converting a list or list of lists:

``` python
my_list = [1,2,3]
print(my_list)

my_array = np.array(my_list)
print(my_array)
```

In [7]:
my_list = [1,2,3]
print(my_list)

my_array = np.array(my_list)
print(my_array)

[1, 2, 3]
[1 2 3]


```python
my_2d_list = [[1,2,3],[4,5,6],[7,8,9]]
print(my_2d_list)

my_matrix = np.array(my_2d_list)
print(my_matrix)
```

In [8]:
my_2d_list = [[1,2,3],[4,5,6],[7,8,9]]
print(my_2d_list)

my_matrix = np.array(my_2d_list)
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


<hr>
<br>
<br>

## Array Attributes and Methods

Let's discuss some useful attributes and methods of an array:

### `.shape`

**Attribute:** Returns an array's shape, all NumPy arrays have this attribute in common.

```python
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(arr.shape)
print(arr)
```

In [12]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arr.shape)
print(arr)

(16,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


<br>

### `.dtype`

**Attribute:** Returns the *single* data type present in numpy array:

**Note**: Numpy Arrays can only contain a *single* datatype.

```python
print(arr.dtype)
```

In [13]:
print(arr.dtype)

int32


<br>

### `.reshape()`
**Method:** Returns an array containing the same data with a new shape.

```python
arr_16_1 = arr.reshape(1,16)

# 16 x 1 matrix
print(arr_16_1.shape)
print(arr_16_1)
```

In [14]:
arr_16_1 = arr.reshape(1,16)

# 16 x 1 matrix
print(arr_16_1.shape)
print(arr_16_1)

(1, 16)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


```python
arr_1_16 = arr.reshape(16,1)

# 1 x 16 matrix
print(arr_1_16.shape)
print(arr_1_16)
```

In [15]:
arr_1_16 = arr.reshape(16,1)

# 1 x 16 matrix
print(arr_1_16.shape)
print(arr_1_16)

(16, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


<br>

### `.max()`, `.min()`, `.argmax()` and `.argmin()`

These are useful methods for finding max or min values. Or to find their index locations ny using argmin or argmax

```python
# Generate an array of length 10, randomly selected from the integers between [1 (inclusive), 20 (non-inclusive)].

ran_arr = np.random.randint(1, 20, 10)
print(ran_arr)
```

In [16]:
ran_arr = np.random.randint(1, 20, 10)
print(ran_arr)

[11 10 16 17 17  4 12 16 12  7]


#### `.max()`

```python
ran_arr.max()
```

In [17]:
ran_arr.max()

17

#### `.argmax()`

```python
ran_arr.argmax()
```

In [18]:
ran_arr.argmax()


3

#### `.min()`

```python
ran_arr.min()
```

In [19]:
ran_arr.min()

4

#### `.argmin()`

```python
ran_arr.argmin()
```

In [22]:
ran_arr.argmin()


5

<hr>
<br>
<br>

## Built-in NumPy Functions

There are lots of built-in ways to generate Arrays

### `.arange()`

Return evenly spaced values within a given interval.

```python
print(np.arange(0,10))
```

In [23]:
print(np.arange(0,10))


[0 1 2 3 4 5 6 7 8 9]


```python
print(np.arange(0,11,2))
```

In [24]:
print(np.arange(0,11,2))

[ 0  2  4  6  8 10]


<br>

### `.zeros()` and `.ones()`

Generate arrays of zeros or ones

```python
print(np.zeros(3))
```

In [26]:
print(np.zeros(3))

[0. 0. 0.]


```python
print(np.zeros((5,5)))
```

In [27]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


```python
print(np.ones((4,6)) * 100)
```

In [43]:
print(np.ones((10,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


```python
print(np.ones((7,3)))
```

In [44]:
print(np.ones((7,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


<br>

### `.linspace()`
Return evenly spaced numbers over a specified interval.

```python
np.linspace(2000,2018,19)
```

In [46]:
np.linspace(2000,2018,19)

array([2000., 2001., 2002., 2003., 2004., 2005., 2006., 2007., 2008.,
       2009., 2010., 2011., 2012., 2013., 2014., 2015., 2016., 2017.,
       2018.])

```python
np.linspace(0,10,50)
```

In [47]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

<hr>
<br>
<br>

## The `random` "Module"

Numpy also has lots of ways to create random number arrays:

### `.random.rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

```python
print(np.random.rand(5))
```

In [66]:
print(np.random.rand(5))

[0.93255736 0.12812445 0.99904052 0.23608898 0.39658073]


```python
print(np.random.rand(5,5))
```

In [52]:
print(np.random.rand(5,5))

[[0.47735053 0.26562749 0.08555685 0.25334008 0.06797576]
 [0.10025419 0.34059591 0.71910118 0.02459534 0.6713838 ]
 [0.99979516 0.88903178 0.00481121 0.06299489 0.1504516 ]
 [0.72254684 0.20172097 0.98496812 0.73234086 0.6694325 ]
 [0.08638876 0.02429717 0.26726588 0.12374885 0.31294744]]


<br>

### `.random.randn()`

Return a sample (or samples) from the **standard normal** distribution. Unlike rand which is uniform:

```python
print(np.random.randn(10))
```

In [68]:
print(np.random.randn(10))

[-1.04514683  0.25759352 -1.9593946  -1.50780766 -0.31529207  0.85817886
  0.07134299 -2.29230928 -1.41555249  0.8858294 ]


```python
print(np.random.randn(5,5))
```

In [58]:
print(np.random.randn(5,5))

[[-9.83488488e-01  1.03369949e-01 -1.91931977e+00  1.37977781e+00
   6.11854704e-01]
 [-6.87639715e-01 -2.96991627e-01 -1.70287733e-02  9.06788311e-01
  -4.49221860e-02]
 [ 1.81079934e+00 -2.20215426e-01  1.21844076e+00 -2.05369812e-03
   1.16323946e+00]
 [ 9.17149998e-01 -2.64032617e+00 -3.16448792e-02 -1.04406706e+00
   3.51876281e-02]
 [-1.08856075e+00 -5.49127616e-01  8.04569525e-01  8.89296405e-01
   1.79028877e+00]]


<br>

### `.random.randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

```python
print(np.random.randint(1,100))
```

In [64]:
np.random.seed(1)
print(np.random.randint(1,100))

38


```python
print(np.random.randint(1,100,10))
```

In [60]:
print(np.random.randint(1,100))

13


In [61]:

print(np.random.randint(1,100,10))

[82  8  6 90 95 22 41 66 42 30]
