# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

```python
import numpy as np
```

In [4]:
import numpy as np
np

<module 'numpy' from 'C:\\Users\\iamal\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

```python
#Creating sample array
arr = np.array([1,2,3,4,5,6,7,8,9,10])

#Show
print(arr)
```

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

#Show
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


<hr>
<br>
<br>

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

```python
#Get a value at an index
arr[8]
```

In [4]:
arr[8]

9

```python
#Get values in a range
print(arr[1:5])
```

In [5]:
print(arr[1:5])

[2 3 4 5]


```python
#Get values in a range
arr[0:5]
```

In [8]:
arr[0:5]
arr[[1,1,1,1,1,1,1]]

array([2, 2, 2, 2, 2, 2, 2])

In [17]:
arr[0:5] = 1
arr

array([ 1,  1,  1,  1,  1,  6,  7,  8,  9, 10])

<hr>
<br>
<br>

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

```python
print(arr)
```

In [2]:

print(arr)

NameError: name 'arr' is not defined

```python
#Setting a value with index range (Broadcasting)
arr[0:5] = 100
print(arr)
```

In [14]:
arr[0:5] = 100
print(arr)

[100 100 100 100 100   6   7   8   9  10]


```python
alist = [1,2,3,4,5,6,7]
alist[0:4] = "h"
print(alist)
```

In [16]:
alist = [1,2,3,4,5,6,7]
alist[0:4] = "h"
print(alist)

['h', 5, 6, 7]


```python
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
print(arr)
```

In [20]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


```python
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
print(slice_of_arr)
```

In [22]:
slice_of_arr = arr[0:6]
print(slice_of_arr)

[0 1 2 3 4 5]


```python
#Change Slice
slice_of_arr[:] = 99

#Show Slice again
print(slice_of_arr)
```

**Now note the changes also occur in our original array!**

```python
print(arr)
```

In [25]:
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


**Data is not copied, it's a view of the original array! This avoids memory problems!**

```python
#To get a copy, we need to be explicit!
arr_copy = arr.copy()
print(arr_copy)
```

In [26]:
arr_copy = arr.copy()
print(arr_copy)

[99 99 99 99 99 99  6  7  8  9 10]


<hr>
<br>
<br>

## Selection

Let's briefly go over how to use boolean comparisons to select certain values

```python
arr = np.arange(1,11)
print(arr)
```

In [28]:
arr = np.arange(1,11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


```python
bool_arr = arr > 6
print(bool_arr)

g_than_six = arr[bool_arr]
print(g_than_six)
```

In [8]:
bool_arr = arr < 6
print(bool_arr)

g_than_six = arr[bool_arr]
print(g_than_six)

[ True  True  True  True  True False False False False False]
[1 2 3 4 5]
